### ISSUE TITLE
AttentiveFP pytorch geometric port

### ISSUE THREAD

**Issue by thegodone** [yvquanli/TrimNet#1]
Thanks for sharing your code. I try to port AttFP to PyG and you have made the comparison in your paper. Do you see a way to make a batch AttFP-PyG based on your code ?

**Comment by yvquanli** [comment]
May you can try this code https://github.com/xiongzhp/AttentiveFP_geometric

**Comment by thegodone** [comment]
this is perfect! thank you so much.
