### ISSUE TITLE
Adding a regression property example

### ISSUE THREAD

**Issue by thegodone** [yvquanli/TrimNet#2]
Can you add a regression example like esol for example ?

**Comment by yvquanli** [comment]
Sorry about that, I’m busy with another work of mine, maybe when I’m free, I can add.
Or you can try to init the Model in model.py with a new Tranier,  just some a few lines of code

**Comment by yvquanli** [comment]
init the model with the params (outdim=1)

**Comment by thegodone** [comment]
I succeed to run the regression modifying lot of your code and got bad results on ESOL I guess your code is not working very well on small data / single regression target.

**Comment by yvquanli** [comment]
You are right.
