### ISSUE TITLE
model for CPI 

### ISSUE THREAD

**Issue by pralaydas** [yvquanli/TrimNet#3]
there is no model information about CPI

**Comment by yvquanli** [comment]
Sorry to see this problem now. Our CPI model is inherited from[ Tsubaki et al. [47]](https://github.com/masashitsubaki). And we only replace the GNN to TrimNet.

**Comment by yvquanli** [comment]
I tried to find the code, but I didn't find it, perhaps you can find some code about CPI from our new method GLAM.
